server:
  port: 8000
spring:
  application:
      name: eureka-client-user-service
eureka:
  client:
#    registerWithEureka: false
#    fetch-registry: false
    serviceUrl:
      defaultZone: http://wujia:123456@eureka7000.com:7000/eureka/
  instance:
    #自定义转跳连接
    status-page-url-path: http://www.wujia.com


    #是否将自己注册到Eureka Server上，默认为true

