server:
  port: 80
spring:
  application:
    name: eureka-hystrix-80-service
eureka:
  client:
    #fetch-registry: false
    serviceUrl:
      defaultZone: http://wujia:123456@eureka7000.com:7000/eureka/
    register-with-eureka: false
  instance:
    #自定义转跳连接
    status-page-url-path: http://www.wujia.com
feign:
  hystrix:
    enabled: true