#server:
#  port: 8081
#spring:
#  application:
#    name: eureka-client-user-service
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://wujia:123456@localhost:8761/eureka/
#  instance:
#    #自定义转跳连接
#    status-page-url-path: http://www.wujia.com
spring:
  profiles:
    active: 8000
